"""Этап 3: integrations, customers, conversations, messages, ai_responses

Раздел 10 ТЗ. Минимум для приёма и хранения сообщений (раздел 18).

Revision ID: 0002_stage3
Revises: 0001_initial
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_stage3'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', name='channel', native_enum=False, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('channel_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'channel', 'external_id', name='uq_customers_business_channel_external')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_business_id'), ['business_id'], unique=False)

    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', name='channel', native_enum=False, length=32), nullable=False),
    sa.Column('credentials_ref', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'ERROR', name='integrationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('webhook_secret_hash', sa.String(length=64), nullable=True),
    sa.Column('external_account_id', sa.String(length=64), nullable=True),
    sa.Column('external_account_name', sa.String(length=120), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'channel', name='uq_integrations_business_channel'),
    sa.UniqueConstraint('channel', 'external_account_id', name='uq_integrations_channel_account')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_webhook_secret_hash'), ['webhook_secret_hash'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', name='channel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'NEEDS_ATTENTION', 'RESOLVED', name='conversationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('HOT', 'WARM', 'COLD', name='leadpriority', native_enum=False, length=32), nullable=False),
    sa.Column('attention_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_updated_at'), ['updated_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('CUSTOMER', 'AI', 'MANAGER', name='sendertype', native_enum=False, length=32), nullable=False),
    sa.Column('external_message_id', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='processingstatus', native_enum=False, length=32), nullable=True),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENT', 'FAILED', name='deliverystatus', native_enum=False, length=32), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sender_type', 'external_message_id', name='uq_messages_conversation_sender_external')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_processing_status'), ['processing_status'], unique=False)

    op.create_table('ai_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('response_message_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'ESCALATED', 'BLOCKED', name='airesponsestatus', native_enum=False, length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('escalation_reason', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    with op.batch_alter_table('ai_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_responses_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_responses_business_id'))

    op.drop_table('ai_responses')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_processing_status'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_messages_business_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_conversations_priority'))
        batch_op.drop_index(batch_op.f('ix_conversations_customer_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_business_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_webhook_secret_hash'))
        batch_op.drop_index(batch_op.f('ix_integrations_business_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_business_id'))

    op.drop_table('customers')
    # ### end Alembic commands ###
